# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 533f531926743e3deccc5a4925b78d5e6c0a55a699550fa4d261806b6563ebff15b48ab7fca45efc7a42d5467c42985efff360fe218629aad41bbbc71cad4560

test:
  secret_key_base: cc1afb2154418dead9789208a6eb6624eb65a2c4c71387862f0aef52bfcd09fc18fbd2ef3b52468f44046bb7b7892d03b5beab1f40566cfa32dbe3dfc354446c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
